name: ci

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/book_code:latest
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER_NAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: 22
                  script: |
                      docker stop book_code
                      docker rm book_code
                      docker rmi ${{ secrets.DOCKERHUB_USERNAME}}/book_code:latest
                      docker run -d --name="book_code" -p 5009:5009  --env-file .env.dev  ${{ secrets.DOCKERHUB_USERNAME}}/book_code:latest
